
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/johnastill/.antigravity/antigravity/bin/"
      - "/Users/johnastill/Documents/Development/google-cloud-sdk/bin/"
      - "/Users/johnastill/.nvm/versions/node/v20.11.0/bin/"
      - "/Users/johnastill/bin/"
      - "/usr/local/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Users/johnastill/Documents/Development/flutter/bin/"
      - "/Users/johnastill/.antigravity/extensions/ms-python.debugpy-2025.18.0-darwin-arm64/bundled/scripts/noConfigScripts/"
    searched_directories:
      - "/Users/johnastill/.antigravity/antigravity/bin/uname"
      - "/Users/johnastill/Documents/Development/google-cloud-sdk/bin/uname"
      - "/Users/johnastill/.nvm/versions/node/v20.11.0/bin/uname"
      - "/Users/johnastill/bin/uname"
      - "/usr/local/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/johnastill/.antigravity/antigravity/bin"
        - "/Users/johnastill/Documents/Development/google-cloud-sdk/bin"
        - "/Users/johnastill/.nvm/versions/node/v20.11.0/bin"
        - "/Users/johnastill/bin"
        - "/usr/local/bin"
        - "/Users/johnastill/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/Library/Apple/usr/bin"
        - "/Users/johnastill/.antigravity/antigravity/bin"
        - "/Users/johnastill/Documents/Development/google-cloud-sdk/bin"
        - "/Users/johnastill/.nvm/versions/node/v20.11.0/bin"
        - "/Users/johnastill/bin"
        - "/Users/johnastill/Documents/Development/flutter/bin"
        - "/Users/johnastill/.antigravity/extensions/ms-python.debugpy-2025.18.0-darwin-arm64/bundled/scripts/noConfigScripts"
        - "/Users/johnastill/Documents/Development/flutter/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 25.2.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/johnastill/.antigravity/antigravity/bin/"
      - "/Users/johnastill/Documents/Development/google-cloud-sdk/bin/"
      - "/Users/johnastill/.nvm/versions/node/v20.11.0/bin/"
      - "/Users/johnastill/bin/"
      - "/usr/local/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Users/johnastill/Documents/Development/flutter/bin/"
      - "/Users/johnastill/.antigravity/extensions/ms-python.debugpy-2025.18.0-darwin-arm64/bundled/scripts/noConfigScripts/"
    searched_directories:
      - "/Users/johnastill/.antigravity/antigravity/bin/install_name_tool"
      - "/Users/johnastill/Documents/Development/google-cloud-sdk/bin/install_name_tool"
      - "/Users/johnastill/.nvm/versions/node/v20.11.0/bin/install_name_tool"
      - "/Users/johnastill/bin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/johnastill/.antigravity/antigravity/bin"
        - "/Users/johnastill/Documents/Development/google-cloud-sdk/bin"
        - "/Users/johnastill/.nvm/versions/node/v20.11.0/bin"
        - "/Users/johnastill/bin"
        - "/usr/local/bin"
        - "/Users/johnastill/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/Library/Apple/usr/bin"
        - "/Users/johnastill/.antigravity/antigravity/bin"
        - "/Users/johnastill/Documents/Development/google-cloud-sdk/bin"
        - "/Users/johnastill/.nvm/versions/node/v20.11.0/bin"
        - "/Users/johnastill/bin"
        - "/Users/johnastill/Documents/Development/flutter/bin"
        - "/Users/johnastill/.antigravity/extensions/ms-python.debugpy-2025.18.0-darwin-arm64/bundled/scripts/noConfigScripts"
        - "/Users/johnastill/Documents/Development/flutter/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
